from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from starbridge_mcp.core.security import sanitize


def _current_status(maturity: str) -> str:
    lowered = maturity.lower()
    if "implemented" in lowered or lowered == "stable":
        return "stable"
    if "planned" in lowered:
        return "planned"
    return "experimental"


@dataclass(frozen=True)
class ToolCapability:
    name: str
    bridge: str
    action: str
    maturity: str
    risk_level: str
    description: str
    side_effects: str
    safe_default: bool
    requires_confirmation: bool
    requires_local_software: bool
    source_projects: tuple[str, ...] = field(default_factory=tuple)
    invocation: str | None = None
    next_step: str | None = None

    @property
    def current_status(self) -> str:
        if self.maturity in {"implemented", "implemented_v1"}:
            return "stable"
        if self.maturity in {"planned", "disabled_v1"}:
            return "planned"
        return "experimental"

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "bridge": self.bridge,
            "action": self.action,
            "maturity": self.maturity,
            "current_status": self.current_status,
            "risk_level": self.risk_level,
            "description": self.description,
            "side_effects": self.side_effects,
            "safe_default": self.safe_default,
            "requires_confirmation": self.requires_confirmation,
            "requires_local_software": self.requires_local_software,
            "source_projects": list(self.source_projects),
            "invocation": self.invocation,
            "next_step": self.next_step,
        }


CAPABILITIES: tuple[ToolCapability, ...] = (
    ToolCapability(
        name="starbridge.status",
        bridge="all",
        action="status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回所有本地创意软件 bridge 的统一状态摘要。",
        side_effects="只读取环境变量和本机服务状态；不会打开用户文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("GLips/Figma-Context-MCP", "IO-AtelierTech/comfyui-mcp"),
        invocation="python -m starbridge_mcp.server status --json",
    ),
    ToolCapability(
        name="starbridge.tools",
        bridge="all",
        action="tools",
        maturity="implemented",
        risk_level="safe_read_only",
        description="列出 KORYAO 当前可用、实验中和计划中的安全工具能力。",
        side_effects="只返回静态能力清单。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "ie3jp/illustrator-mcp-server"),
        invocation="python -m starbridge_mcp.server tools --json",
    ),
    ToolCapability(
        name="starbridge.control_plan",
        bridge="all",
        action="control_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="根据创作目标为 Codex 选择软件桥，并返回只读、分阶段的安全控制计划。",
        side_effects="只返回路由、工具顺序和质量门；不启动软件、不读私有文件、不执行写入。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("modelcontextprotocol/specification",),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="starbridge.safe_roots",
        bridge="all",
        action="safe_roots",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回 KORYAO 公开安全根目录、可写输出边界和 MCP roots 对齐建议。",
        side_effects="只返回仓库相对路径和边界说明；不扫描私有目录。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "modelcontextprotocol/specification",
            "adobe/generator-app-remote-mcp-server-generic",
        ),
        invocation="python -m starbridge_mcp.server roots --json",
    ),
    ToolCapability(
        name="starbridge.evidence_init",
        bridge="all",
        action="evidence_init",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回 EvidenceManifest 初始化预览和默认输出位置，不读取私有素材。",
        side_effects="只返回结构化预览，不启动桌面软件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "joenorton/comfyui-mcp-server"),
        invocation="python -m starbridge_mcp.server evidence --init --json",
    ),
    ToolCapability(
        name="starbridge.evidence_validate",
        bridge="all",
        action="evidence_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 EvidenceManifest 的结构、路径脱敏和状态字段。",
        side_effects="只读取已声明 manifest 路径。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "joenorton/comfyui-mcp-server"),
        invocation="python -m starbridge_mcp.server evidence --validate --json",
    ),
    ToolCapability(
        name="starbridge.job_status",
        bridge="all",
        action="job_status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回统一的作业状态词汇和当前 evidence 关联摘要。",
        side_effects="只读取 manifest 摘要，不触发执行。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "joenorton/comfyui-mcp-server"),
        invocation="python -m starbridge_mcp.server job-status --json",
    ),
    ToolCapability(
        name="starbridge.operation_context",
        bridge="all",
        action="operation_context",
        maturity="implemented",
        risk_level="safe_read_only",
        description="把调用方传入的安全 before/after 指标转换为可链式状态差异和证据引用。",
        side_effects="纯内存处理；不访问文件、网络或桌面软件，不接收文档名、图层名或任意路径。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "alisaitteke/photoshop-mcp",
            "modelcontextprotocol/specification",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="starbridge.recipe_list",
        bridge="all",
        action="recipe_list",
        maturity="implemented",
        risk_level="safe_read_only",
        description="List safe cross-bridge KORYAO recipes without launching desktop software.",
        side_effects="Returns static workflow plans only; does not read private assets or write files.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "dcc-mcp/dcc-mcp-photoshop",
            "alecc08/comfyui-mcp",
            "ahujasid/blender-mcp",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="starbridge.recipe_plan",
        bridge="all",
        action="recipe_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Return a dry-run action plan, quality gates, and evidence requirements for one KORYAO recipe.",
        side_effects="Plans only; real bridge execution remains behind each tool's confirmation gates.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "dcc-mcp/dcc-mcp-photoshop",
            "southleft/figma-console-mcp",
            "joenorton/comfyui-mcp-server",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="starbridge.recipe_evidence",
        bridge="all",
        action="recipe_evidence",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Preview a standardized EvidenceManifest for one KORYAO recipe, including quality gates and asset manifest entries.",
        side_effects="Returns a sanitized manifest preview only; does not materialize files or launch local software.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "joenorton/comfyui-mcp-server",
            "dcc-mcp/dcc-mcp-photoshop",
            "southleft/figma-console-mcp",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="cad_autocad.environment_probe",
        bridge="cad_autocad",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查 AutoCAD 可执行文件、COM 注册和 pywin32 线索。",
        side_effects="不打开 DWG/DXF，不控制 CAD 软件，不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp", "AnCode666/multiCAD-mcp"),
        invocation="python examples/cad_bridge/probe.py --json",
    ),
    ToolCapability(
        name="autocad_dxf.status",
        bridge="autocad_dxf",
        action="status",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查离线 DXF bridge 是否能做 CAD plan 校验和 dry-run。",
        side_effects="不需要 AutoCAD，不打开 DWG/DXF。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp",),
        invocation="python examples/cad/generate_dxf_plan.py --dry-run",
    ),
    ToolCapability(
        name="autocad_dxf.validate_cad_plan",
        bridge="autocad_dxf",
        action="validate_cad_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 CAD JSON plan 的单位、图层和实体结构。",
        side_effects="只处理传入 JSON，不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp", "AnCode666/multiCAD-mcp"),
    ),
    ToolCapability(
        name="autocad_dxf.write_dxf",
        bridge="autocad_dxf",
        action="write_dxf",
        maturity="implemented",
        risk_level="guarded_local_write",
        description="把已校验 CAD plan 写成测试 DXF；默认应该先 dry-run。",
        side_effects="dry_run=False 时只允许写入 examples/cad/output。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("puran-water/autocad-mcp",),
        next_step="保持真实 AutoCAD COM/MCP 控制与离线 DXF export 分离。",
    ),
    ToolCapability(
        name="comfyui.system_probe",
        bridge="comfyui",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="读取 ComfyUI /system_stats 与 /object_info，确认服务和节点是否可用。",
        side_effects="只访问本机或配置的 ComfyUI API，不提交生成任务。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        invocation="python examples/comfy_bridge/probe.py --json",
    ),
    ToolCapability(
        name="comfyui.queue_snapshot",
        bridge="comfyui",
        action="queue_snapshot",
        maturity="implemented",
        risk_level="safe_read_only",
        description="默认只返回计划；显式 probe 时读取 loopback /queue 并输出脱敏队列与 backpressure。",
        side_effects=(
            "不提交或取消任务，不读取 workflow/history/output；live 模式只发送一次 loopback GET。"
        ),
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=(
            "artokun/comfyui-mcp",
            "IO-AtelierTech/comfyui-mcp",
            "modelcontextprotocol/specification",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="comfyui.progress_monitor",
        bridge="comfyui",
        action="progress_monitor",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "默认只返回计划；显式 connect 时监听 loopback /ws，并输出脱敏、单调的任务进度与 stalled 判定。"
        ),
        side_effects=(
            "不提交或取消任务，不读取 workflow/history/output；live 模式只建立有界的 loopback WebSocket 连接。"
        ),
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=(
            "Comfy-Org/ComfyUI",
            "artokun/comfyui-mcp",
            "websocket-client/websocket-client",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="comfyui.job_snapshot",
        bridge="comfyui",
        action="job_snapshot",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "默认只返回计划；显式 probe 时按 canonical job ID 读取 loopback 单任务状态，"
            "只输出哈希 ID、终态和有界输出数量。"
        ),
        side_effects=(
            "不提交或取消任务；不返回 workflow、output、preview、异常正文或 traceback；"
            "live 模式只发送一次直接 loopback GET。"
        ),
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=(
            "Comfy-Org/ComfyUI",
            "comfy-addons/comfyui-sdk",
            "artokun/comfyui-mcp",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="comfyui.workflow_validate",
        bridge="comfyui",
        action="workflow_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 workflow JSON 是否为 API format，并检查关键节点引用。",
        side_effects="只读取公开示例 workflow 或用户明确传入的文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
        invocation="python examples/comfy_bridge/validate_workflow.py --json",
    ),
    ToolCapability(
        name="comfyui.workflow_build_plan",
        bridge="comfyui",
        action="workflow_build_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="把自然语言目标转换成 ComfyUI dry-run 工作流构建计划，不读取私有图片或模型目录。",
        side_effects="只返回任务类型、输入要求、节点要求和安全提示；不提交队列。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "IO-AtelierTech/comfyui-mcp",
            "artokun/comfyui-mcp",
            "joenorton/comfyui-mcp-server",
        ),
    ),
    ToolCapability(
        name="comfyui.workflow_build",
        bridge="comfyui",
        action="workflow_build",
        maturity="implemented",
        risk_level="safe_read_only",
        description="为支持的 txt2img 场景生成 API-like workflow JSON，并附带校验结果和哈希。",
        side_effects="只在内存里生成 workflow；不访问文件系统，不提交 ComfyUI。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfyui.workflow_repair",
        bridge="comfyui",
        action="workflow_repair",
        maturity="implemented",
        risk_level="safe_read_only",
        description="修复缺失节点、空输入和核心连线，输出 dry-run 修复后的 txt2img workflow。",
        side_effects="只处理传入的 workflow JSON 或安全默认草案；不提交队列。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("IO-AtelierTech/comfyui-mcp", "joenorton/comfyui-mcp-server"),
    ),
    ToolCapability(
        name="comfyui.agent_run",
        bridge="comfyui",
        action="agent_run",
        maturity="implemented",
        risk_level="guarded_local_process",
        description="执行 build/validate/repair/submit/status 一体化 ComfyUI agent 流程，区分已提交与完成、失败、取消终态，默认 dry-run。",
        side_effects="confirm_run=true 时会访问本机 ComfyUI API，并可能触发其输出目录写入。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=(
            "IO-AtelierTech/comfyui-mcp",
            "artokun/comfyui-mcp",
            "joenorton/comfyui-mcp-server",
        ),
    ),
    ToolCapability(
        name="comfyui.generation_result",
        bridge="comfyui",
        action="generation_result",
        maturity="implemented",
        risk_level="safe_read_only",
        description="按显式 prompt ID 续查异步生成终态，并返回稳定 asset_id 与脱敏输出清单。",
        side_effects="仅向 loopback ComfyUI 发送有界 history GET；不提交任务，不读取图片字节。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=(
            "joenorton/comfyui-mcp-server",
            "artokun/comfyui-mcp",
        ),
    ),
    ToolCapability(
        name="comfyui.generation_cancel",
        bridge="comfyui",
        action="generation_cancel",
        maturity="implemented",
        risk_level="guarded_local_process",
        description="默认 dry-run；显式确认后只取消一个指定 ComfyUI 任务。",
        side_effects=(
            "confirm_cancel=true 时向 loopback ComfyUI 发送单任务取消请求；"
            "不回退到会影响其他任务的全局 interrupt。"
        ),
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=(
            "Comfy-Org/ComfyUI",
            "artokun/comfyui-mcp",
            "joenorton/comfyui-mcp-server",
        ),
    ),
    ToolCapability(
        name="comfyui.asset_list",
        bridge="comfyui",
        action="asset_list",
        maturity="implemented",
        risk_level="safe_read_only",
        description="按最新优先列出当前会话中仍可继续迭代的脱敏 asset_id。",
        side_effects="无；不访问 ComfyUI 或文件系统，不返回 workflow、prompt、模型、文件名、图像或路径。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "joenorton/comfyui-mcp-server",
            "artokun/comfyui-mcp",
        ),
    ),
    ToolCapability(
        name="comfyui.asset_metadata",
        bridge="comfyui",
        action="asset_metadata",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查当前会话 asset_id 的内存 provenance 是否仍可用于受控重生成。",
        side_effects="无；不访问 ComfyUI、不读取文件，也不返回 workflow、prompt、模型或路径。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "joenorton/comfyui-mcp-server",
            "artokun/comfyui-mcp",
        ),
    ),
    ToolCapability(
        name="comfyui.regenerate",
        bridge="comfyui",
        action="regenerate",
        maturity="implemented",
        risk_level="guarded_local_process",
        description="用当前会话 asset_id 的内存 provenance 覆写参数并重新提交 txt2img。",
        side_effects="默认 dry-run；confirm_run=true 时向 loopback ComfyUI 提交新任务并写其本地输出。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=(
            "artokun/comfyui-mcp",
            "joenorton/comfyui-mcp-server",
        ),
    ),
    ToolCapability(
        name="comfy.workflow_draft",
        bridge="comfyui",
        action="workflow_draft",
        maturity="implemented",
        risk_level="safe_read_only",
        description="为 txt2img、img2img、inpaint、upscale 生成只读 placeholder workflow 草案并立即校验。",
        side_effects="只返回安全占位 graph 和校验报告；不读本地素材，不发请求。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "joenorton/comfyui-mcp-server"),
    ),
    ToolCapability(
        name="comfy.workflow_compose",
        bridge="comfyui",
        action="workflow_compose",
        maturity="implemented",
        risk_level="safe_read_only",
        description="用固定安全模块组合 ComfyUI graph，生成可审查的 placeholder workflow。",
        side_effects="只在内存中组合节点并校验；不读取私有输入，不提交任务。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp", "joenorton/comfyui-mcp-server"),
    ),
    ToolCapability(
        name="comfy.workflow_template_list",
        bridge="comfyui",
        action="workflow_template_list",
        maturity="implemented",
        risk_level="safe_read_only",
        description="列出仓库内公开 ComfyUI 工作流模板注册表及其安全状态。",
        side_effects="只读取打包的公开模板元数据；不访问网络，不提交任务。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("joenorton/comfyui-mcp-server", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_template_get",
        bridge="comfyui",
        action="workflow_template_get",
        maturity="implemented",
        risk_level="safe_read_only",
        description="读取单个公开 ComfyUI 工作流模板及其校验结果。",
        side_effects="只返回模板 JSON 和校验摘要；不读私有素材，不提交任务。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("joenorton/comfyui-mcp-server", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_from_template",
        bridge="comfyui",
        action="workflow_from_template",
        maturity="implemented",
        risk_level="safe_read_only",
        description="基于公开模板和安全 composer 模块生成 placeholder workflow。",
        side_effects="只在内存中组合与校验工作流；不访问网络或私有文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("joenorton/comfyui-mcp-server", "artokun/comfyui-mcp"),
    ),
    ToolCapability(
        name="comfy.workflow_lifecycle_summary",
        bridge="comfyui",
        action="workflow_lifecycle_summary",
        maturity="implemented",
        risk_level="safe_read_only",
        description="为已审查 ComfyUI workflow 生成脱敏 job / asset 生命周期摘要。",
        side_effects="只返回节点、资产角色、确认门和 evidence 预览；不暴露模型名、素材路径或生成图，不提交队列。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("joenorton/comfyui-mcp-server", "artokun/comfyui-mcp"),
        invocation="python examples/comfy_bridge/workflow_lifecycle.py --template-id txt2img_basic_v1 --json",
    ),
    ToolCapability(
        name="comfy.workflow_visualize",
        bridge="comfyui",
        action="workflow_visualize",
        maturity="implemented",
        risk_level="safe_read_only",
        description="把内联 ComfyUI API workflow 转换成 Mermaid 图和脱敏结构摘要。",
        side_effects="只分析内存中的节点和连线；不输出 prompt、模型名或输入值，不访问文件和网络。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("artokun/comfyui-mcp",),
    ),
    ToolCapability(
        name="drawio.probe",
        bridge="diagramforge",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Probe the DiagramForge headless compiler and optional Draw.io desktop exporter.",
        side_effects="Reads executable availability only; does not open diagrams or start desktop software.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp", "jgraph/drawio-desktop"),
        invocation="python examples/drawio_bridge/cli.py probe",
    ),
    ToolCapability(
        name="drawio.capabilities",
        bridge="diagramforge",
        action="capabilities",
        maturity="implemented",
        risk_level="safe_read_only",
        description="List native inputs, recipes, stable patching, validation, and export support.",
        side_effects="Returns static typed capability metadata only.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp", "lgazo/drawio-mcp-server"),
    ),
    ToolCapability(
        name="drawio.plan",
        bridge="diagramforge",
        action="plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Compile and validate a deterministic Draw.io document in memory.",
        side_effects="No files, browsers, or desktop applications are opened.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp",),
        invocation="python examples/drawio_bridge/cli.py plan --recipe research-framework-v1",
    ),
    ToolCapability(
        name="drawio.create",
        bridge="diagramforge",
        action="create",
        maturity="implemented_v1",
        risk_level="guarded_local_write",
        description="Create native .drawio, editable SVG preview, and structural manifest files.",
        side_effects="Requires confirm_write and writes only to ignored DiagramForge safe output roots.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp",),
        invocation="python examples/drawio_bridge/cli.py demo --confirm-write",
    ),
    ToolCapability(
        name="drawio.inspect",
        bridge="diagramforge",
        action="inspect",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Inspect one explicit safe-root .drawio document and return stable element hashes.",
        side_effects="Reads only the exact repository-relative safe path supplied by the caller.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("lgazo/drawio-mcp-server",),
    ),
    ToolCapability(
        name="drawio.patch",
        bridge="diagramforge",
        action="patch",
        maturity="implemented_v1",
        risk_level="guarded_local_write",
        description="Apply transactional stable-ID patches while proving unrelated element hashes stayed stable.",
        side_effects="Requires confirm_write and updates one explicit .drawio document plus its SVG preview.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("lgazo/drawio-mcp-server",),
    ),
    ToolCapability(
        name="drawio.rollback",
        bridge="diagramforge",
        action="rollback",
        maturity="implemented_v1",
        risk_level="guarded_local_write",
        description="Restore the validated one-level checkpoint for one explicit Draw.io document.",
        side_effects="Requires confirm_write and rotates only the target document's ignored checkpoint.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("lgazo/drawio-mcp-server",),
    ),
    ToolCapability(
        name="drawio.validate",
        bridge="diagramforge",
        action="validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Validate XML, IDs, connectors, bounds, overlap, text fit, and contrast.",
        side_effects="Reads one explicit safe-root .drawio file and returns a structural report.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp",),
    ),
    ToolCapability(
        name="drawio.export",
        bridge="diagramforge",
        action="export",
        maturity="implemented_v1",
        risk_level="guarded_local_write",
        description="Export an editable SVG or a PDF through an installed Draw.io desktop CLI.",
        side_effects="Requires confirm_write; SVG is headless, while PDF requires local Draw.io app.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("jgraph/drawio-mcp", "jgraph/drawio-desktop"),
    ),
    ToolCapability(
        name="drawio.handoff.plan",
        bridge="diagramforge",
        action="handoff_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Build a hash-bound import plan for Canvas, Photoshop, or Illustrator.",
        side_effects="Reads one explicit safe artifact and returns no absolute source path; downstream writes remain separately confirmed.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(),
    ),
    ToolCapability(
        name="drawio.batch",
        bridge="diagramforge",
        action="batch",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Build deterministic idempotent batch plans with bounded concurrency and resume IDs.",
        side_effects="Plans in memory only; each future materialization remains separately confirmed.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("lgazo/drawio-mcp-server",),
    ),
    ToolCapability(
        name="photoshop.session_info",
        bridge="photoshop",
        action="session_info",
        maturity="experimental",
        risk_level="safe_read_only",
        description="通过 Windows COM 读取 Photoshop session 和当前文档摘要。",
        side_effects="需要已授权 Photoshop；不打开 PSD，不保存导出。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server", "alisaitteke/photoshop-mcp"),
        invocation="powershell -ExecutionPolicy Bypass -File examples/photoshop_bridge/scripts/document_info.ps1",
    ),
    ToolCapability(
        name="photoshop.document_info",
        bridge="photoshop",
        action="document_info",
        maturity="experimental_demo",
        risk_level="safe_read_only",
        description="Read active Photoshop document metadata through COM without opening private PSD files.",
        side_effects="Requires an authorized local Photoshop session; does not save or export files.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:info",
    ),
    ToolCapability(
        name="photoshop.create_demo_document",
        bridge="photoshop",
        action="create_demo_document",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Create a public sandbox Photoshop layer demo.",
        side_effects="dry_run is the default; real output requires confirm_write and is restricted to examples/output/photoshop.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo:plan",
    ),
    ToolCapability(
        name="photoshop.export_demo_preview",
        bridge="photoshop",
        action="export_demo_preview",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Export PNG and JPG previews from the Photoshop sandbox demo only.",
        side_effects="dry_run is the default; real export requires confirm_export and is restricted to examples/output/photoshop.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo",
    ),
    ToolCapability(
        name="photoshop.run_demo",
        bridge="photoshop",
        action="run_demo",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Run the Photoshop sandbox create, export, and manifest sequence.",
        side_effects="dry_run is the default; real run requires confirm_write and confirm_export.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
        invocation="npm.cmd run photoshop:demo",
    ),
    ToolCapability(
        name="photoshop.subject_extract",
        bridge="photoshop",
        action="subject_extract",
        maturity="experimental",
        risk_level="guarded_local_write",
        description="对用户明确传入的图片运行主体选择并导出测试 PNG。",
        side_effects="会打开输入图片并写出输出 PNG；输入和输出路径必须由参数传入。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server", "alisaitteke/photoshop-mcp"),
        next_step="后续 MCP tool 必须保留参数化路径和输出脱敏。",
    ),
    ToolCapability(
        name="photoshop.recipe_list",
        bridge="photoshop",
        action="recipe_list",
        maturity="implemented",
        risk_level="safe_read_only",
        description="列出当前公开安全的 Photoshop recipe 层能力，而不是直接暴露任意底层写工具。",
        side_effects="只返回受审查 recipe 清单。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp", "loonghao/photoshop-python-api-mcp-server"),
    ),
    ToolCapability(
        name="photoshop.recipe_plan",
        bridge="photoshop",
        action="recipe_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="为 Photoshop sandbox recipe 生成 dry-run 计划、输出清单和质量门。",
        side_effects="只校验参数和输出边界，不启动 Photoshop。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="photoshop.recipe_validate",
        bridge="photoshop",
        action="recipe_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验 Photoshop recipe 的 manifest、路径脱敏和 sandbox 输出约束。",
        side_effects="只返回结构化验证结果，不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("loonghao/photoshop-python-api-mcp-server",),
    ),
    ToolCapability(
        name="photoshop.recipe_run",
        bridge="photoshop",
        action="recipe_run",
        maturity="implemented",
        risk_level="guarded_local_write",
        description="执行受控 Photoshop recipe；默认 dry_run，真实写入必须显式确认。",
        side_effects="dry_run=False 时只允许写入 examples/output/photoshop。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp", "loonghao/photoshop-python-api-mcp-server"),
    ),
    ToolCapability(
        name="photoshop.recipe_debug",
        bridge="photoshop",
        action="recipe_debug",
        maturity="implemented",
        risk_level="safe_read_only",
        description="返回 Photoshop recipe 的重试策略、验证门和本地排障建议。",
        side_effects="只返回调试建议，不触发本地软件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.capabilities",
        bridge="photoshop",
        action="capabilities",
        maturity="implemented",
        risk_level="safe_read_only",
        description="List typed Photoshop categories, progressive profiles, recipes, and truthful maturity.",
        side_effects="Static read-only metadata; live connection remains a separate ps.probe truth state.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "AdobeDocs/uxp-photoshop-plugin-samples",
            "loonghao/photoshop-python-api-mcp-server",
        ),
    ),
    ToolCapability(
        name="ps.recipe.compile",
        bridge="photoshop",
        action="recipe_compile",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Compile typed simple, advanced, and batch recipes with bounded repair and quality gates.",
        side_effects="Builds an in-memory plan only; planned-only categories are reported rather than executed.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp", "dcc-mcp/dcc-mcp-photoshop"),
    ),
    ToolCapability(
        name="ps.batch.plan",
        bridge="photoshop",
        action="batch_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Build a single-host FIFO batch with deterministic IDs, idempotency, and resume checkpoints.",
        side_effects="Plans only and never opens assets or starts Photoshop.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("dcc-mcp/dcc-mcp-photoshop",),
    ),
    ToolCapability(
        name="ps.result.verify",
        bridge="photoshop",
        action="result_verify",
        maturity="implemented",
        risk_level="safe_read_only",
        description="Verify sandbox, state readback, artifact hashes, and native reopen gates.",
        side_effects="Validates caller-supplied sanitized evidence only; no private files are read.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.probe",
        bridge="photoshop",
        action="probe",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Photoshop v1 local bridge probe with COM fallback, mock mode, and UXP or node-proxy readiness fields.",
        side_effects="Read-only by default; does not open PSD files or export outputs.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "loonghao/photoshop-python-api-mcp-server",
            "mikechambers/adb-mcp",
            "dcc-mcp-photoshop",
        ),
        next_step="Run this first, then use document, layers, preview, or evidence tools against the same job_id.",
    ),
    ToolCapability(
        name="ps.document.info",
        bridge="photoshop",
        action="document_info",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Inspect the active Photoshop document through the local bridge without opening files from MCP.",
        side_effects="Reads an already-open active document only; no save, export, or script execution.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("loonghao/photoshop-python-api-mcp-server", "mikechambers/adb-mcp"),
    ),
    ToolCapability(
        name="ps.layers.list",
        bridge="photoshop",
        action="layers_list",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Return a review-oriented layer tree from the active Photoshop document.",
        side_effects="Reads the active document only; no writes or exports.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp", "bubblydoo/uxp-toolkit"),
    ),
    ToolCapability(
        name="ps.selection.subject",
        bridge="photoshop",
        action="selection_subject",
        maturity="implemented_v1_plan_only",
        risk_level="level_1_sandbox_write",
        description="Plan or mock a subject-selection request without mutating a real PSD in v1.",
        side_effects="Defaults to dry_run; live Photoshop selection changes are still disabled.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp", "00bx/00bx-photoshop-mcp"),
    ),
    ToolCapability(
        name="ps.layer.rename",
        bridge="photoshop",
        action="layer_rename",
        maturity="implemented_v1_plan_only",
        risk_level="level_1_sandbox_write",
        description="Plan or mock a layer rename request without mutating a real PSD in v1.",
        side_effects="Defaults to dry_run; live layer rename is disabled.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.layer.move",
        bridge="photoshop",
        action="layer_move",
        maturity="implemented_v1_plan_only",
        risk_level="level_1_sandbox_write",
        description="Plan or mock a layer reorder request without mutating a real PSD in v1.",
        side_effects="Defaults to dry_run; live layer move is disabled.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.layer.visibility",
        bridge="photoshop",
        action="layer_visibility",
        maturity="implemented_v1_plan_only",
        risk_level="level_1_sandbox_write",
        description="Plan or mock a layer visibility change without mutating a real PSD in v1.",
        side_effects="Defaults to dry_run; live visibility changes are disabled.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.preview.export",
        bridge="photoshop",
        action="preview_export",
        maturity="implemented_v1",
        risk_level="level_1_sandbox_write",
        description="Stage a preview export to sandbox or output with an EvidenceManifest for review.",
        side_effects="Defaults to dry_run; real writes require requires_confirmation=true and stay inside sandbox or output.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("mikechambers/adb-mcp", "dcc-mcp-photoshop"),
    ),
    ToolCapability(
        name="ps.get_preview",
        bridge="photoshop",
        action="get_preview",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Return cheap preview (base64 or path) of active doc for vision models. Read-only.",
        side_effects="No writes; safe for iterative vision use.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp", "mikechambers/adb-mcp"),
    ),
    ToolCapability(
        name="ps.get_state",
        bridge="photoshop",
        action="get_state",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Lightweight state snapshot (doc info, layer count, active). No pixels.",
        side_effects="Read-only cheap state for before/after comparison.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.camera_raw.tune",
        bridge="photoshop",
        action="camera_raw_tune",
        maturity="implemented_v1_plan_only",
        risk_level="level_2_confirmed_write",
        description="Plan and validate Camera Raw tuning parameters for blue artwork or fabric texture photos.",
        side_effects="Defaults to dry_run; real apply requires confirm_apply=true and is blocked until a verified BatchPlay descriptor fixture exists.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("bubblydoo/uxp-toolkit", "dcc-mcp-photoshop"),
        next_step="Record a verified Camera Raw Filter descriptor with Alchemist or Photoshop Action listener before enabling live apply.",
    ),
    ToolCapability(
        name="ps.evidence.capture",
        bridge="photoshop",
        action="evidence_capture",
        maturity="implemented_v1",
        risk_level="level_1_sandbox_write",
        description="Capture a structured EvidenceManifest JSON for a Photoshop bridge job.",
        side_effects="Defaults to dry_run; confirmed writes stay inside sandbox/evidence or output/evidence.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=False,
        source_projects=("dcc-mcp-photoshop", "00bx/00bx-photoshop-mcp"),
    ),
    ToolCapability(
        name="ps.batchplay.validate",
        bridge="photoshop",
        action="batchplay_validate",
        maturity="implemented_v1",
        risk_level="level_0_read_only",
        description="Validate BatchPlay descriptors and classify risk before any execution path exists.",
        side_effects="Does not execute BatchPlay or arbitrary scripts.",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("bubblydoo/uxp-toolkit", "dcc-mcp-photoshop"),
    ),
    ToolCapability(
        name="ps.batchplay.execute_confirmed",
        bridge="photoshop",
        action="batchplay_execute_confirmed",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved confirmed-write BatchPlay execution path, intentionally disabled in v1.",
        side_effects="Would modify Photoshop state; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("bubblydoo/uxp-toolkit", "dcc-mcp-photoshop"),
    ),
    ToolCapability(
        name="ps.script.execute_confirmed",
        bridge="photoshop",
        action="script_execute_confirmed",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved confirmed-write Photoshop script execution path, intentionally disabled in v1.",
        side_effects="Would run Photoshop-side code; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("mikechambers/adb-mcp", "bubblydoo/uxp-toolkit"),
    ),
    ToolCapability(
        name="ps.history.undo",
        bridge="photoshop",
        action="history_undo",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved history undo path, intentionally disabled in v1.",
        side_effects="Would mutate document history; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.mask.refine",
        bridge="photoshop",
        action="mask_refine",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved mask-refine tool, intentionally disabled in v1.",
        side_effects="Would change layers and masks; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("00bx/00bx-photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.smartobject.place",
        bridge="photoshop",
        action="smartobject_place",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved smart-object placement tool, intentionally disabled in v1.",
        side_effects="Would place assets into a working document; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("00bx/00bx-photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.adjustment.apply",
        bridge="photoshop",
        action="adjustment_apply",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved adjustment tool, intentionally disabled in v1.",
        side_effects="Would modify document appearance; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.text.edit",
        bridge="photoshop",
        action="text_edit",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved text-edit tool, intentionally disabled in v1.",
        side_effects="Would modify document text layers; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("alisaitteke/photoshop-mcp",),
    ),
    ToolCapability(
        name="ps.export.psd_copy",
        bridge="photoshop",
        action="export_psd_copy",
        maturity="disabled_v1",
        risk_level="level_2_confirmed_write",
        description="Reserved PSD copy export tool, intentionally disabled in v1.",
        side_effects="Would write a PSD copy into sandbox or output; currently always refused.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("00bx/00bx-photoshop-mcp",),
    ),
    ToolCapability(
        name="illustrator.document_info",
        bridge="illustrator",
        action="document_info",
        maturity="experimental",
        risk_level="safe_read_only",
        description="通过状态探针检查 Illustrator COM 线索；后续扩展当前文档、图层、画板和坐标系摘要。",
        side_effects="不打开私有 .ai 文件，不导出 SVG/PDF/PNG。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="python -m starbridge_mcp.mcp_server",
        next_step="先稳定只读 COM/session 探针，再评估 preflight。",
    ),
    ToolCapability(
        name="illustrator.create_demo_artboard",
        bridge="illustrator",
        action="create_demo_artboard",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Create a public sandbox Illustrator vector artboard demo.",
        side_effects="dry_run is the default; real output requires confirm_write and is restricted to examples/output/illustrator.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo:plan",
    ),
    ToolCapability(
        name="illustrator.export_demo_assets",
        bridge="illustrator",
        action="export_demo_assets",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Export SVG, PNG, and PDF from the Illustrator sandbox demo only.",
        side_effects="dry_run is the default; real export requires confirm_export and is restricted to examples/output/illustrator.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo",
    ),
    ToolCapability(
        name="illustrator.run_demo",
        bridge="illustrator",
        action="run_demo",
        maturity="experimental_demo",
        risk_level="guarded_local_write",
        description="Run the Illustrator sandbox artboard, export, and manifest sequence.",
        side_effects="dry_run is the default; real run requires confirm_write and confirm_export.",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="npm.cmd run illustrator:demo",
    ),
    ToolCapability(
        name="illustrator.preflight",
        bridge="illustrator",
        action="preflight",
        maturity="implemented",
        risk_level="safe_read_only",
        description="对传入的脱敏 Illustrator 文档摘要做只读 preflight，例如链接、颜色模式和文本对象风险。",
        side_effects="只处理调用方传入的摘要；不打开 .ai、不修复、不保存、不导出。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("ie3jp/illustrator-mcp-server",),
        invocation="python examples/illustrator_bridge/scripts/preflight_plan.py --json",
        next_step="本机可先运行 illustrator.document_info，再把脱敏摘要传入 preflight。",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_backend_plan",
        bridge="illustrator",
        action="color_vectorize_backend_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="根据调用方提供的脱敏特征，在原生 Illustrator 与 headless SVG fallback 间做保守选择。",
        side_effects="纯内存 dry-run；不读取图片、不探测环境、不执行 CLI 或 Adobe。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("visioncortex/vtracer",),
        next_step="仅 planned 状态可按 next_action 继续；needs_user/blocked 不得静默降级。",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_plan",
        bridge="illustrator",
        action="color_vectorize_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="为用户明确授权的单张 PNG/JPEG 生成 Photoshop + Illustrator 彩色矢量化应用矩阵和质量闸门。",
        side_effects="纯内存计划；不读取图片、不启动 Adobe 软件、不扫描目录、不上传云端。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "AdobeDocs/illustrator-scripting-guide",
            "ie3jp/illustrator-mcp-server",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
        next_step="计划确认后，只把本次明确传入的单个文件交给受控执行器。",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_validate",
        bridge="illustrator",
        action="color_vectorize_validate",
        maturity="implemented",
        risk_level="safe_read_only",
        description="校验脱敏轮廓、色差、感知相似度、节点预算和矢量 hard gates。",
        side_effects="只处理调用方提供的数字和布尔指标；不读取参考图或预览文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("AdobeDocs/illustrator-scripting-guide",),
        invocation="python -m starbridge_mcp.mcp_server",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_compare",
        bridge="illustrator",
        action="color_vectorize_compare",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "比较一张明确授权的 PNG/JPEG 与 Illustrator sandbox PNG，自动计算轮廓、"
            "CIE76 D65 色差、8x8 block SSIM 和矢量可编辑性证据。"
        ),
        side_effects=(
            "只读取两个明确文件；候选图必须位于 examples/output/illustrator，"
            "不递归扫描、不返回路径、像素或元数据。"
        ),
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "python-pillow/Pillow",
            "w3c/csswg-drafts",
            "AdobeDocs/illustrator-scripting-guide",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
        next_step="未通过时按 findings 调整 Image Trace 参数，再生成新的 sandbox PNG 比较。",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_repair_plan",
        bridge="illustrator",
        action="color_vectorize_repair_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "把脱敏比较 findings 编译成最多三轮的确定性 Image Trace 参数修复计划，"
            "并生成无路径的 execute dry-run 与 post-execute compare 契约。"
        ),
        side_effects="纯内存 dry-run；不读取图片、不启动 Adobe、不写文件、不执行脚本。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "alisaitteke/photoshop-mcp",
            "visioncortex/vtracer",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
        next_step=(
            "先用 next_execute_template 复核下一轮 dry-run；运行时绑定明确源文件与双确认后"
            "执行 sandbox trace，再按 post_execute_compare 和 iteration_control 比较或停止。"
        ),
    ),
    ToolCapability(
        name="illustrator.color_vectorize_advance",
        bridge="illustrator",
        action="color_vectorize_advance",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "把 execute 后的脱敏 compare 结果收敛为 complete、下一轮 repair 或终止，"
            "并强制最多三轮。"
        ),
        side_effects="纯内存 dry-run；不接收路径、不读取图片、不启动 Adobe、不写文件。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "alisaitteke/photoshop-mcp",
            "modelcontextprotocol/specification",
        ),
        invocation="python -m starbridge_mcp.mcp_server",
        next_step="仅 repair_planned 可调用 next_repair_plan；complete 或终止状态不得继续自动执行。",
    ),
    ToolCapability(
        name="illustrator.color_vectorize_execute",
        bridge="illustrator",
        action="color_vectorize_execute",
        maturity="experimental_local_executor",
        risk_level="guarded_local_write",
        description="用固定 JSX 对明确传入的单张 PNG/JPEG 做 Illustrator 彩色 Image Trace，并输出 sandbox AI/SVG/PNG。",
        side_effects="默认 dry-run；真实执行需要授权声明、输入单文件、confirm_write、confirm_export 和已运行的 Illustrator。",
        safe_default=False,
        requires_confirmation=True,
        requires_local_software=True,
        source_projects=(
            "AdobeDocs/illustrator-scripting-guide",
            "krVatsal/illustrator-mcp",
        ),
        invocation=(
            "powershell -ExecutionPolicy Bypass -File "
            "examples/illustrator_bridge/scripts/color_vectorize.ps1"
        ),
        next_step="导出后仍需调用质量验证；未通过前保持 needs_visual_review。",
    ),
    ToolCapability(
        name="blender.environment_probe",
        bridge="blender",
        action="probe",
        maturity="implemented",
        risk_level="safe_read_only",
        description="检查 Blender 可执行文件和可选 MCP 目录。",
        side_effects="不打开 .blend，不运行任意 Python，不下载模型。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("ahujasid/blender-mcp",),
        invocation="python examples/blender_bridge/probe.py --json",
    ),
    ToolCapability(
        name="blender.scene_plan",
        bridge="blender",
        action="scene_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description="生成公开安全的 Blender 基础场景 dry-run 计划。",
        side_effects="不启动 Blender，不打开 .blend，不执行任意 Python，不读取贴图或资产库。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("ahujasid/blender-mcp",),
        invocation="python examples/blender_bridge/scene_plan.py --json",
        next_step="后续若加入真实 render，必须继续使用固定模板并写入忽略目录。",
    ),
    ToolCapability(
        name="blender.reference_reconstruction_plan",
        bridge="blender",
        action="reference_reconstruction_plan",
        maturity="implemented",
        risk_level="safe_read_only",
        description=(
            "生成参考图驱动的 Blender 重建 dry-run 计划，明确分割、深度/点云初始化、"
            "单视图量测、渲染反查和误差门槛。"
        ),
        side_effects="不读取图片，不启动 Blender，不打开 .blend，不运行任意 Python，不下载外部模型。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=(
            "facebookresearch/vggt",
            "ByteDance-Seed/depth-anything-3",
            "facebookresearch/sam2",
            "IDEA-Research/GroundingDINO",
            "facebookresearch/pytorch3d",
            "NVlabs/nvdiffrast",
        ),
        invocation="python examples/blender_bridge/reference_reconstruction_plan.py --json",
        next_step="真实重建必须在本地确认后生成同相机渲染对比、误差报告和 evidence manifest。",
    ),
    ToolCapability(
        name="jianying_capcut.draft_probe",
        bridge="jianying_capcut",
        action="draft_probe",
        maturity="research",
        risk_level="safe_read_only",
        description="检查剪映/CapCut 可执行文件和草稿目录配置。",
        side_effects="不读取 draft_content.json，不导出视频，不触碰账号。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("sun-guannan/VectCutAPI", "xuliang2024/cutcli-cookbook"),
        invocation="python examples/capcut_jianying_bridge/probe.py --json",
    ),
    ToolCapability(
        name="jianying_capcut.draft_structure",
        bridge="jianying_capcut",
        action="draft_structure",
        maturity="implemented",
        risk_level="safe_read_only",
        description="只读统计剪映 / CapCut 草稿目录顶层结构，不输出草稿名或素材路径。",
        side_effects="只检查环境变量指定目录的顶层计数；不递归扫描，不读取 draft_content.json 或 draft_info.json。",
        safe_default=True,
        requires_confirmation=False,
        requires_local_software=False,
        source_projects=("sun-guannan/VectCutAPI", "xuliang2024/cutcli-cookbook"),
        invocation="python examples/capcut_jianying_bridge/draft_structure.py --json",
        next_step="后续生成测试草稿前，先验证依赖许可和本机草稿格式兼容性。",
    ),
)

# Centralized bridge metadata (moved/shared to reduce duplication with server.py).
# BRIDGE_PROFILES and related maps are defined here as the single source for high-level summaries.
# Detailed per-action info is in CAPABILITIES.
BRIDGE_NAME_MAP = {
    "ComfyUI": "comfyui",
    "Blender": "blender",
    "CAD": "autocad",
    "DiagramForge": "diagramforge",
    "Photoshop": "photoshop",
    "Illustrator": "illustrator",
    "JianyingCapCut": "jianying_capcut",
}

BRIDGE_ALIASES = {
    "cad_autocad": "autocad",
    "cad_dxf": "autocad_dxf",
    "capcut_jianying": "jianying_capcut",
}

BRIDGE_PROFILES: dict[str, dict[str, Any]] = {
    "diagramforge": {
        "display_name": "DiagramForge structured drawing bridge",
        "software": "Draw.io compatible headless compiler",
        "probe_type": "Deterministic compiler and optional desktop executable probe",
        "required_env": ["DRAWIO_EXE (optional)"],
        "ready_when": "The headless compiler is available; desktop PDF and live MCP remain separate.",
        "safety_boundary": "No private-directory scans; confirmed writes stay in ignored safe roots.",
        "current_actions": [
            "status",
            "probe",
            "plan",
            "create",
            "inspect",
            "patch",
            "rollback",
            "validate",
            "export",
            "handoff_plan",
            "batch",
        ],
    },
    "comfyui": {
        "display_name": "ComfyUI 图像生成桥",
        "software": "ComfyUI",
        "probe_type": "HTTP read-only probe",
        "required_env": ["STARBRIDGE_COMFYUI_URL", "COMFY_ROOT", "COMFY_LAUNCHER"],
        "ready_when": "ComfyUI API 可访问，且 /system_stats 与 /object_info 可读。",
        "safety_boundary": "只读检查本机 API，不读取模型文件，不提交生成图片。",
        "current_actions": ["status", "probe"],
    },
    "photoshop": {
        "display_name": "Photoshop 修图桥",
        "software": "Adobe Photoshop",
        "probe_type": "Windows COM / executable configuration probe",
        "required_env": ["PHOTOSHOP_EXE"],
        "ready_when": "pywin32 可用；严格探测时能连接 Photoshop.Application COM。",
        "safety_boundary": "不打开 PSD，不读取素材路径，不写出导出结果。",
        "current_actions": ["status", "probe"],
    },
    "illustrator": {
        "display_name": "AI 矢量文件桥",
        "software": "Adobe Illustrator",
        "probe_type": "Windows COM / executable configuration probe",
        "required_env": ["ILLUSTRATOR_EXE"],
        "ready_when": "pywin32 可用；严格探测时能连接 Illustrator.Application COM。",
        "safety_boundary": "不打开 .ai 私有工程；彩色描摹只读取用户明确传入的单图并写入 sandbox。",
        "current_actions": [
            "status",
            "probe",
            "color_vectorize_plan",
            "color_vectorize_backend_plan",
            "color_vectorize_validate",
            "color_vectorize_compare",
            "color_vectorize_repair_plan",
            "color_vectorize_advance",
            "color_vectorize_execute",
        ],
    },
    "blender": {
        "display_name": "Blender 三维场景桥",
        "software": "Blender",
        "probe_type": "Executable and optional MCP directory probe",
        "required_env": ["BLENDER_EXE", "BLENDER_MCP_DIR"],
        "ready_when": "找到 blender.exe；可选找到 Blender MCP 桥目录。",
        "safety_boundary": "不打开私有 .blend，不渲染资产，不下载外部模型；参考图重建先只输出 dry-run 计划和误差门槛。",
        "current_actions": ["status", "probe", "scene_plan", "reference_reconstruction_plan"],
    },
    "autocad": {
        "display_name": "CAD 工程制图桥",
        "software": "AutoCAD / CAD",
        "probe_type": "MCP project, executable, and win32com probe",
        "required_env": ["AUTOCAD_EXE", "STARBRIDGE_CAD_MODE"],
        "ready_when": "AutoCAD MCP 子项目存在，且找到 AutoCAD 可执行文件或 COM 线索。",
        "safety_boundary": "不打开客户 DWG/DXF，不写真实项目输出；离线 DXF 与真实 CAD 控制分开处理。",
        "current_actions": ["status", "probe"],
    },
    "autocad_dxf": {
        "display_name": "AutoCAD / DXF 离线生成桥",
        "software": "DXF headless bridge",
        "probe_type": "schema and dry-run status",
        "required_env": [],
        "ready_when": "无需 AutoCAD；CAD plan 可校验，DXF 写入默认 dry-run。",
        "safety_boundary": "不打开 DWG，不控制 AutoCAD；dry_run=False 时只允许写入 examples/cad/output。",
        "current_actions": ["status", "validate_cad_plan", "summarize_plan", "write_dxf"],
    },
    "jianying_capcut": {
        "display_name": "剪映/CapCut 草稿桥",
        "software": "剪映 / CapCut",
        "probe_type": "Executable and draft directory configuration probe",
        "required_env": ["JIANYING_EXE", "JIANYING_DRAFTS_DIR", "CAPCUT_EXE", "CAPCUT_DRAFTS_DIR"],
        "ready_when": "找到剪映或 CapCut 可执行文件，并确认对应草稿目录。",
        "safety_boundary": "只读检查配置，不读取草稿内容，不导出视频，不触碰账号。",
        "current_actions": ["status", "probe"],
    },
}


def list_capabilities(*, bridge: str = "all", include_guarded: bool = True) -> list[dict[str, Any]]:
    selected = []
    for capability in CAPABILITIES:
        if bridge != "all" and capability.bridge not in {bridge, "all"}:
            continue
        if not include_guarded and not capability.safe_default:
            continue
        selected.append(capability.to_dict())
    return sanitize(selected)


def _bridge_overview(capabilities: list[dict[str, Any]], *, bridge: str) -> dict[str, Any]:
    names = ["all"] if bridge == "all" else ["all", bridge]
    if bridge == "all":
        names.extend(BRIDGE_PROFILES)

    overview: dict[str, Any] = {}
    for name in dict.fromkeys(names):
        items = [item for item in capabilities if item["bridge"] == name]
        if name != "all" and not items and name not in BRIDGE_PROFILES:
            continue
        safe_tools = sorted(item["name"] for item in items if item["safe_default"])
        guarded_tools = sorted(item["name"] for item in items if not item["safe_default"])
        profile = BRIDGE_PROFILES.get(name, {})
        overview[name] = {
            "display_name": profile.get("display_name", "KORYAO global tools"),
            "software": profile.get("software", "KORYAO"),
            "tool_count": len(items),
            "safe_default_tool_count": len(safe_tools),
            "guarded_tool_count": len(guarded_tools),
            "requires_local_software_tool_count": sum(
                1 for item in items if item["requires_local_software"]
            ),
            "statuses": sorted({item["current_status"] for item in items}),
            "risk_levels": sorted({item["risk_level"] for item in items}),
            "safe_tools": safe_tools,
            "guarded_tools": guarded_tools,
            "readiness": profile.get("ready_when"),
            "safety_boundary": profile.get("safety_boundary"),
        }
    return overview


def capability_summary(*, bridge: str = "all", include_guarded: bool = True) -> dict[str, Any]:
    capabilities = list_capabilities(bridge=bridge, include_guarded=include_guarded)
    bridge_categories: dict[str, list[str]] = {}
    for item in capabilities:
        bucket = bridge_categories.setdefault(item["bridge"], [])
        if item["action"] not in bucket:
            bucket.append(item["action"])
    return sanitize(
        {
            "ok": True,
            "framework": "KORYAO",
            "manifest_version": "starbridge.capabilities.v2",
            "action": "tools",
            "bridge": bridge,
            "capability_count": len(capabilities),
            "capabilities": capabilities,
            "bridge_categories": {
                name: sorted(values) for name, values in bridge_categories.items()
            },
            "bridge_overview": _bridge_overview(capabilities, bridge=bridge),
            "planner_hints": {
                "safe_discovery_sequence": [
                    "starbridge.safe_roots",
                    "starbridge.status",
                    "starbridge.recipe_list",
                    "starbridge.recipe_plan",
                    "starbridge.recipe_evidence",
                ],
                "evidence_tools": [
                    "starbridge.evidence_init",
                    "starbridge.evidence_validate",
                    "starbridge.recipe_evidence",
                    "starbridge.job_status",
                ],
                "observation_tools": ["starbridge.operation_context"],
                "confirmed_action_rule": (
                    "Call safe_default tools first; guarded tools require the matching "
                    "confirm_write, confirm_export, or confirm_run flag and must stay inside safe roots."
                ),
            },
            "adoption_policy": {
                "third_party_source": "third_party_research is local-only and ignored by Git.",
                "copy_policy": "借鉴架构和接口形状；不直接复制第三方源码到公开仓库。",
                "write_policy": "写入类能力必须参数化路径、默认 dry-run 或需要用户确认。",
            },
        }
    )
